/**
 * users.js
 * =========
 *
 * Placeholder route generated by Express scaffolding.
 *
 * This route is not actively used in the Travlr application
 * but remains part of the default Express project structure.
 */

var express = require('express');
var router = express.Router();

/* GET users listing. */
router.get('/', function(req, res, next) {
  res.send('respond with a resource');
});

module.exports = router;
